sudo: false
dist: trusty
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - "npm i -g npm@latest"
install:
  - npm install
before_script:
  - npm prune
